# Project Configuration

project:
  name: "Financial Translation POC"
  version: "0.1.0"
  log_level: "INFO"

data:
  sources:
    - name: "IMF Reports"
      path: "data/sources/imf"
    - name: "Central Bank Documents"
      path: "data/sources/central_bank"
    - name: "Financial News"
      path: "data/sources/news"
  
  glossary:
    path: "data/glossary/financial_terms.csv"
    update_frequency: "weekly"
  
  preprocessing:
    max_sequence_length: 128
    min_sentence_length: 5
    train_split: 0.8
    val_split: 0.1
    test_split: 0.1

model:
  base_model: "mBART-large-50"  # Options: mBART, mT5, custom
  fine_tuning:
    learning_rate: 2e-5
    batch_size: 16
    epochs: 10
    warmup_steps: 500
    weight_decay: 0.01
  
  glossary_integration:
    method: "constrained_decoding"  # Options: constrained_decoding, attention_biasing
    confidence_threshold: 0.85

evaluation:
  metrics:
    - "bleu"
    - "ter"
    - "meteor"
    - "bertscore"
  
  human_evaluation:
    evaluators_per_document: 2
    evaluation_aspects:
      - "accuracy"
      - "fluency"
      - "terminology"
      - "style"

api:
  host: "0.0.0.0"
  port: 8000
  max_request_size: "10MB"
  rate_limit: 100  # requests per minute

security:
  encryption_enabled: true
  authentication_required: true
  data_retention_days: 30 